apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
#- gotk-sync.yaml
patches:
- target:
    version: v1
    group: apps
    kind: Deployment
    name: image-reflector-controller
    namespace: flux-system
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --gcp-autologin-for-gcr
- target:
    version: v1
    group: ""
    kind: ServiceAccount
    name: image-reflector-controller
    namespace: flux-system
  patch: |-
    - op: add
      path: /metadata/annotations/spec/
      value: kingdon-test-gcr-sa.dx-kingdon.iam.gserviceaccount.com
images: # []
- name: ghcr.io/fluxcd/image-reflector-controller
  newName: docker.io/somma/image-reflector-controller
  newTag: test-autologin-18df01042
