apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: rancher.io/local-path
  name: pvc-2478ba23-430c-41b3-a73f-7838a7e2cb84
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /opt/local-path-provisioner/pvc-2478ba23-430c-41b3-a73f-7838a7e2cb84_minio-juozas_minio-storage
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - msigaming
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
