apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
    volume.kubernetes.io/selected-node: msigaming
  labels:
    app.kubernetes.io/instance: minio-stage
    app.kubernetes.io/name: minio-stage
  name: minio-stage
  namespace: minio-stage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
  volumeName: pvc-61decf71-3bed-406f-8836-18dcbb3ef89e
