apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
    volume.kubernetes.io/selected-node: msigaming
  labels:
    app.kubernetes.io/instance: minio-storage
    app.kubernetes.io/name: minio-storage
  name: minio-storage
  namespace: minio-juozas
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
  volumeName: pvc-2478ba23-430c-41b3-a73f-7838a7e2cb84
