apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kube-oidc-proxy
  namespace: flux-system
spec:
  interval: 75m
  retryInterval: 10m
  timeout: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/kube-oidc-proxy
  dependsOn:
    - name: my-secrets
    - name: certificates
    - name: ingress-nginx
  prune: true
  wait: true
  suspend: false
