apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: blog
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`blog.teamhephy.info`)
    kind: Rule
    services:
    - kind: Service
      name: blog
      namespace: blog
      port: 80
