kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deis:deis-example
  labels:
    app: deis-example
    heritage: deis
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deis:deis-example
subjects:
- kind: ServiceAccount
  name: deis-example
  namespace: deis
