apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hephy
spec:
  chart:
    spec:
      sourceRef:
        kind: GitRepository
        name: hephy-workflow-beta
        namespace: deis
      version: ^2.24.0-0
  interval: 15m15s
  timeout: 10m0s
  storageNamespace: deis
  targetNamespace: deis
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - kind: ClusterRole
            apiVersion: rbac.authorization.k8s.io/v1
            metadata:
              name: deis:deis-controller
            rules:
            - apiGroups: [""]
              resources: ["namespaces"]
              verbs: ["get", "list", "create", "delete"]
            - apiGroups: [""]
              resources: ["services"]
              verbs: ["get", "list", "create", "update", "delete"]
            - apiGroups: [""]
              resources: ["nodes"]
              verbs: ["get", "list"]
            - apiGroups: [""]
              resources: ["events"]
              verbs: ["list", "create"]
            - apiGroups: [""]
              resources: ["secrets"]
              verbs: ["list", "get", "create", "update", "delete"]
            - apiGroups: [""]
              resources: ["replicationcontrollers"]
              verbs: ["get", "list", "create", "update", "delete"]
            - apiGroups: [""]
              resources: ["replicationcontrollers/scale"]
              verbs: ["get", "update"]
            - apiGroups: [""]
              resources: ["pods/log"]
              verbs: ["get"]
            - apiGroups: [""]
              resources: ["pods"]
              verbs: ["get", "list", "create", "delete"]
            - apiGroups: [""]
              resources: ["resourcequotas"]
              verbs: ["get", "create"]
            - apiGroups: ["extensions", "apps"]
              resources: ["replicasets"]
              verbs: ["get", "list", "delete", "update"]
            - apiGroups: ["extensions", "apps"]
              resources: ["deployments"]
              verbs: ["get", "list", "create", "update", "delete"]
            - apiGroups: ["extensions", "apps"]
              resources: ["deployments/scale", "replicasets/scale"]
              verbs: ["get", "update", "patch"]
            - apiGroups: ["extensions", "autoscaling"]
              resources: ["horizontalpodautoscalers"]
              verbs: ["get", "list", "create", "update", "delete"]
            - apiGroups: ["networking.k8s.io"]
              resources: ["ingresses"]
              verbs: ["get", "list", "watch", "create", "update", "delete"]
          - kind: Deployment
            apiVersion: apps/v1
            metadata:
              name: deis-controller
            spec:
              template:
                spec:
                  containers:
                    - name: deis-controller
                      image: kingdonb/controller:git-7beda111
          - kind: Service
            apiVersion: v1
            metadata:
              name: deis-builder
            spec:
              loadBalancerIP: 10.17.12.205        # deis-builder.nerdland.local
          - kind: DaemonSet
            apiVersion: apps/v1
            metadata:
              name: deis-monitor-telegraf
            "$patch": delete
          - kind: Deployment
            apiVersion: apps/v1
            metadata:
              name: deis-minio
            spec:
              template:
                spec:
                  containers:
                  - name: deis-minio
                    volumeMounts:
                    - mountPath: /home/minio
                      name: deis-hephy
                  volumes:
                  - name: deis-hephy
                    persistentVolumeClaim:
                      claimName: deis-hephy
         # - kind: Ingress
         #   apiVersion: extensions/v1beta1
         #   metadata:
         #     name: controller-api-server-ingress-http
         #     namespace: deis
         #     annotations:
         #       kubernetes.io/ingress.class: internal
         #   # spec:
         #   #   ingressClassName: internal
  values:
    controller:
      platform_domain: deis.hephy.pro
    global:
      experimental_native_ingress: true
      use_cni: true
      gunicorn_workers: 5
      database_location: off-cluster
      grafana_location: off-cluster
      influxdb_location: off-cluster
    database:
      postgres:
        name: hephy
        username: hephy_admin
        host: 10.17.12.227
        port: "5432"
  valuesFrom:
  - kind: Secret
    name: deis-db-admin-password
    valuesKey: password
    targetPath: database.postgres.password
