apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: 85-kuby-test
  namespace: flux-system
spec:
  interval: 60m0s
  retryInterval: 6m0s
  timeout: 4m0s
  sourceRef:
    kind: GitRepository
    name: flux-sync
  path: ./apps/kuby-test
  dependsOn:
  # - name: 11-certificates
  # - name: 12-persistence
  # - name: traefik-api-crds
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: kuby-release-config
  prune: true
  wait: false
 #suspend: false
