---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: 93-scrob-prod
  namespace: flux-system
spec:
  interval: 1m0s
  timeout: 2m0s
  retryInterval: 30s
  path: ./manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: scrob-web
  dependsOn:
    - name: infrastructure
   #- name: 11-certificates
    - name: 20-my-secrets
    - name: 30-ingress-nginx
