apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-sync
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: staging
  url: https://github.com/kingdonb/bootstrap-repo
