apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
spec:
  chart:
    spec:
      chart: harbor
      sourceRef:
        kind: HelmRepository
        name: harbor
      version: 1.8.1
  interval: 15m15s
  timeout: 2m0s
  values:
    notary:
      enabled: false
    expose:
      tls:
        certSource: secret
        secretName: harbor-ingress
      ingress:
        hosts:
          core: img.hephy.pro
          #notary: not.hephy.pro
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
    externalURL: https://img.hephy.pro
    persistence:
      imageChartStorage:
        type: s3
        s3:
          region: us-east-1
          bucket: harbor-storage
          regionendpoint: https://minio.hephy.pro

  valuesFrom:
  - kind: Secret
    name: minio-user
    valuesKey: accesskey
    targetPath: persistence.imageChartStorage.s3.accesskey
  - kind: Secret
    name: minio-user
    valuesKey: secretkey
    targetPath: persistence.imageChartStorage.s3.secretkey

  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - apiVersion: networking.k8s.io/v1
            kind: Ingress
            metadata:
              name: harbor-ingress
            spec:
              ingressClassName: internal
         #- apiVersion: networking.k8s.io/v1
         #  kind: Ingress
         #  metadata:
         #    name: harbor-ingress-notary
         #  spec:
         #    ingressClassName: internal
