apiVersion: v1
data:
    identity: ENC[AES256_GCM,data:Soo/yyTXYAQDuwNf+VUdd2FbhrzuJCyqaTmM+7LL77J085zGPWDG137TkkewuLurIqnApZqvaMQcwnFKWytVsIRY9loF9jbHSyY61Q6gDDwZlRbuVzmVHodDtuzFDaXV6njmcUzV2JDVnT3RVAdHYy4WBm/xXvTkpVnKZ2SNKycA+IGk9tp+yy63OtKzDqXPIc8N6VBpmsANXJrgLwnXiDefPud7AR77IbA0JoJ4twPbUCW/cLjikmJp9wM7frEstrKe0LW+j6FUasfvnPb3tEAQvP+/LTyZVZfE9uTg1zbiuA1dlofYpkX53o3vtTd4KWtdUJAOOzhjOjdpbaRAp+ZCjd7H6v0QTJeNPK6gN4U3Tuh6v1YFbISY6CFgcydz+kHZFfcUMNcr5qPkv1ilVEjcXCsFBCU8Ryd5xkUefmD+B7uBdBdsIpRu+bFA9csiYeS/qxCqiU8Wm7XNdTzI7dLUGoUB+/SRMOWVktrMSkNYiDFZoXRRErX9vlxqDqLx9zW48ZPXYjKI1LBgb713ZnjbUe/dpjtl,iv:H9rNeID/MjTVaxcpJ9uE9Wfnab3kcZgXNqqKEPBKQ2c=,tag:Ji5kDGIGMSRSF+8jVBuQSA==,type:str]
    identity.pub: ENC[AES256_GCM,data:vJXuFLN7TGOQEONQq7iAVikizH/HDo/tqr0OU0LGa78K5OrEaiIcp+zSwYzds9dq5luITji8hLcPR2ZrYcZRhNc6LzCZLjtXZNhbx4KQrHKxodJNBiduqWe+GgygZeWKwkC303h9wgOqqqBSms6JY+N/mh3xeStnYvp/iY+jQnMYcY4bMtkQzSYK6r2zfPNWavT4m7DNUMljl4M9r511z6bOi6gmvebm0FmaL5Kdqcw7UF46tDDnJ1l5uhjhtzu/0vpOajuqwf7KVizAoL8P40XEd5MMxwXvj6snt7y4DEhiFu3Ir1NPNpipHbZr/UBCoZ4oBOnlE26bI4bKa+JUN2fuasS6IUOyW3jXMWAaumaU1FlL,iv:4/TExfS+klCwV+lqEhh9BV9Du4MuZ9V1Imy18n7dHVA=,tag:smUCEO4AdK9fI3T9aVErTg==,type:str]
    known_hosts: ENC[AES256_GCM,data:/DHCXQ0VFnbVrFb8tdhqHEJFGQN9LhihXZQ59p3c6aw3RzvNPikVOqQM3A4vkfY25xR6KCL/19EqgBThU3keEaa/gHr4TimD5svAX8rO1EgwIzXvbU03kgWIUCLPkKHxp/dXGrlFzskzLJONoPirk6coaysqgq37bjQAWSqk9AsG2VA/WDBka8/Q+yAqGM7kiJZEWxOsUp+aIMv4ayO2bRYocFG7uoE7yQQf6YZSwNar8CiBpzupsdx4ufUUsCezDNFFLI7l4DRpco38dnC8bMrfIf15yRn9mmK3EH5WQcVjw0Qp,iv:EtkJHKljd1Rtvz0dd1cms5EmlcrXPnap5aASe0v4++I=,tag:vuIdmqrHPHrGjHVgrEsXpQ==,type:str]
kind: Secret
metadata:
    name: flux-system-rw
    namespace: kubytest-production
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-11T17:32:45Z"
    mac: ENC[AES256_GCM,data:2AJr061voDn0Q8mBfFmdMIuSAaR/Qf/Nji7sMrhXuCJNMvbTWtqTjfDqsNFY/k3skHWILRBGmfB61cP790QrS6geKl2qFO9J1zP9mY5G6Rn8vsCsWe+Ft8UaL+8+NMGe9hCHUoVOQGGJjLxKtAR3MfiWlHOiWo56H6sN+1TDU0U=,iv:NZh/Vn9Edak/yHoLXeXCW37O+T3/P6s9GZrEDQ03dsc=,tag:mjLQJ79rBSp/suZuPsNScQ==,type:str]
    pgp:
        - created_at: "2021-12-11T17:22:47Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA06rSFOpPqRMAQ//RuMZh0BEFnlRWhr4++a/dGo2VSLDILkmlG1hoAu8NYii
            oAq/yjEt5Oo832bHxSCUcnpyj6xkcH2w781gxzbliKvE75Qtse0rJ9+Li67ibZES
            PIBcvBEJTcqAbliEi5KJpXLC7/+VyrdythbK2iIjDOuH4OeRalTzM7iytMtvc8AC
            x/8/wXicDjUWu1g8c5laWY+o59c6Xb08ANt23vI9r/oiWLQ9HNzqg7M/wz4+pNCT
            b88cmfyXn8DAmt9cMqLyZ3S0pjDQqx1hEQuKFEj7Z9KqE7S+9+bX3WfjdbZCN5EV
            YJ+EE7PpSD/aYH1owe3SFJXELj4YJ1sHFz+OOTP0MG6sh4FrVaIOVej4iKTq7uum
            WRWevqUO9uVlJwz8oRS14zhEJDKCcisXytz4QtVYImr5OnLrEB6INmr0X29jmCEe
            h43jehzgn8mcJrq8QIUVPjGhO5reG25061VR/S6M3VRIJheOnSx2YHJwhLWk0b5B
            Zp6XJUK6z5CEQZdHYXEoyRd450qx8h7gJIvBG6jG3MGhcH3hrvyTUC/T1I22h5fF
            FmGUQ9TMds5RW/pTWOTnhuXS1wzsP5Iyi2wx+5bC9W26X63fO57o/5s1FBYu52zx
            rrCnnGrwaDDVOsf13mspZDQPUPaB22rzeFj0L0CHLMzatWYgry6X3em+QK99YqvS
            XgFM2b4OxooZrBAu9DFdh/8qjfDAJsqQHd0h2nfRWFTS2HGO/808QdLlQCLlNvIK
            gI0tVVgSdn/ZAfSApIMy6efCK7Z5XNSOpuu9UcjkEYxnMwqtkpHe4cSS3NBwAIo=
            =wfJ4
            -----END PGP MESSAGE-----
          fp: A883B02E14B7EAF0A6BDAF69ECD23C5916E31D4F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
