apiVersion: v1
data:
    slack-api-url: ENC[AES256_GCM,data:0KPgcyjQnua/F6kcMTQIb3QR9ddxpi9d4gvKRKV8hZI0F5eD13elGTiO74sj6nw73odIrAPfsWugv+Grjn1PwqZWNRgxYtZuBjYkKo/DxzNT1iQ5OH3H1EC97M1HW8UNhRXI0WTydNJWLVQk,iv:aKw0z+Fzl7ADh2aUf/LzgHXA8LbLOjS2o5IJcI6/PxA=,tag:5JdF5LddlngOr+G8bJLnTg==,type:str]
kind: Secret
metadata:
    name: slack-api-url
    namespace: monitoring
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-16T17:14:57Z"
    mac: ENC[AES256_GCM,data:1aDCOXpB1j+SPk4yTLWiVRCxX6CYLDzh3aLV6yHOGHToBehHn6l12e0urk7PIw+oApgBzO67/OJY7c4K+P8XUlQ7r7m1QB6t4c7cDJfpDulqOdnyHJKPJp4G9HA8GqDVSNpue2AlXw1wEkykB1Qxf3iY0O/xU9gSyg2D2ZIARq0=,iv:wDuMlDjHkLVxL8fyTB+Hd0+kAq9HFF0CSDZt5ILly9s=,tag:vYQY4sE4bEzrpx/QU7D1KQ==,type:str]
    pgp:
        - created_at: "2022-01-16T17:14:56Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA06rSFOpPqRMAQ/9Hf7uG3bNLRMSM4+ta8LXfUarWzirNwFL2zcjjVeCa9v1
            OqKnlsj2ovJIdy1oY1Jr5VyUl3ycmSTbv80c9k2Eft+J8QJ0wTYnKz/6qE2xTrAw
            rMujy6ZIKjJfOkhoqu/bx9QyunfUbdIB4WJ/xBvDBeh2e6C/jtgRHnH+f+ZytYlY
            wz/b7TjCBEjBfu8ei3HI2DSDOW4TG9GiPJbOdlEefVGLlBokoy2RudITupRvyF81
            6tX5a3GlRewfCoFvoiT7yz5n29n94nSfHkVX6AupU/MGv6kJxFhBl5ph0wyamvRk
            p07Xml78KaN0A51aaYpdKJjFQrG+gWzt9ndI7KdEOXs6gOlE3KREBkd1Ix65bnKv
            dhByzsxq502b8yIa6vDULoXW9uAy+59F+Lwv4fD1eRIZzmmNRNHotgNHI8+N34o1
            5SZJrBDCSTADdF93Mp88NZvJ0xJa+RO3n71z+eDwzUKa6FsGJZpkM6Uq6twxBZTc
            LUjg0Ph31ud6B0m08GOGOAB7I2O/fwuw/1kTha+ySl7GrZDYLB7ONHXw7DITAEb/
            iI8Un8XwQOtGFcT3BgsS1vt32Hj+6gNI1lHCJd94mHdLqVlNgcd8kCH6rYgf1nh4
            8Xe35w+wU4PSxPdPp9g48WtMPcQP3dFLo3aLk6PWb7YrA/sk7godd1FEg8ldnIzS
            XgHhowuu8hH9maIVImDb36TmkgPTNJEqimpSo00j5h00MOuRPrBq3IUhz8BNWOVc
            1IJ7+4BEmJgjetjg++9lbHnvYGizV5OwCKogdLhJzm1ZOyd/Ioik53BvstaWLvA=
            =mQjE
            -----END PGP MESSAGE-----
          fp: A883B02E14B7EAF0A6BDAF69ECD23C5916E31D4F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
