apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:ht/MyDHZx814EW2ijlXNMe6d3ljx+du4SzlhOhuUegJdAqFru2zQDRiz/cMG1KH9UyKs9XntCyzt3hc9h9VWI4W7nYsXFVZ5s3wDnwrI8NA080coqHS5z8yMmRgn9rpUAM5bp/7U50fUYGyDnaEtfXrr2Db3gpanHb5vBGgXwvCxZrm0NF+Nh9IfMDq5eKx5TKInock68kIxbe7qPQaCLJYWVBzViJWL+Y7ujRYT19A5Euol4RCSVcQsCV/90pKxt5g0Ggs+tkYTsRdIQQRY2Shg7+X/riJN8HjtA5oW4SYs11WH+AmcbBM7bENjlWFfzX2cZOELZ7UiF1bWvOo75w==,iv:8oR6jmTB2fXfws7DFxX/+O1bdB8FzB26II37VUmnYPc=,tag:/RNPfr5a/akwPc458GLWuw==,type:str]
kind: Secret
metadata:
    name: scrob-registry-secret
    namespace: scrob-production
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-03T17:13:55Z"
    mac: ENC[AES256_GCM,data:+tV/XXcv1d1UBkYjUmLKODirr3SkFfUMU1mUzb3Usbgl7sBYawoOLCsyGfFrq4sFHe+QvVNjeWliDZFIovFoVikpl8W2jDbq/Dm4ohBDraEbjKXr3H/WXOCZwsxNyITDU942ASkbNEU79yiQqLtzHcpeJ2k+Gx83YAM3v2qC4vs=,iv:miuGgcqPttDorxjFkKxYqTp4IvVfZXUWPI5LL8Yb3Vc=,tag:LHEUmlBnypWD3Z+EN+AAig==,type:str]
    pgp:
        - created_at: "2022-01-03T17:13:54Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA06rSFOpPqRMARAAl4FwOuXNIygXWePaOZ3IYAphRWVh19PB+uMP5z2ScT4p
            FIRlFrTviBs8vBT5dkCKafQ7c1+coZElG5ykPE95lQ3HGDei2jC5Ov5+LVlNmwJT
            BeSYkcBYLMD2fadGM+MC2xSwgUgzO04vk4Hd3eCS+A2KuYNEtVSLYYOrlMh/2VOB
            R7YjpG090ZLgbY/gXL+HQ3LL9cNMdISKHro34Kmpy84Hb1KFSyrddOlbF7F8mtLt
            EB71DerVwn8ON60/9nHaIA++ceWC4/nMoC62LpQCwh3IKdQvvvrYaaUmdSa7fYxY
            eIE2Oak6qLTovaq33gPZPvb6Sjzv4RuGEW3JLZsJCbKrZxbzxHUqLfLLw6vdkt3B
            P+SIbSR8InuMr+tloTEGKb7D1zrB2SbBb3zpXBsCWt8B3WfDGfqWgmBFRHyIaMiU
            ouLcMNyib3AiKyI7XBEEFOhA4tSb3GWUqXx28cEbe/iqkSTefsOYksBUHHiJ4Kg1
            oy83wnsJRw7PmQplNPJP+IOzhStU+tTSYNxlB98fsCGCMFEwZvz7dZHZFbLizJFV
            qTeR8u9ZvKpbyz000wHL3Pub8ACfg0kaQuqkilyN3KS/osgpc4TowGMBBFbfGAhJ
            HCnzUCQVqEr+sfIDtmjX89uySvv4lHHF235bzqo0tdKeR8oS5lSP48uh+iEvBQzS
            XgGBBBDEzoP3sbBZ69RvQ5S0hEgd09SF7q6bgvaRCFbHysCyisquvDvX7sKulZ0g
            oz6ATrLQhM/QZhWpG4TJIT2Y0p++m8ZeTSwUa5lMWaH0Nl1u6pYk0iFaim0I6CQ=
            =9W4n
            -----END PGP MESSAGE-----
          fp: A883B02E14B7EAF0A6BDAF69ECD23C5916E31D4F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
data:
    RAILS_MASTER_KEY: ENC[AES256_GCM,data:c3CtUUtNkHgdz5yZo8k5TdnK/woo/sJqGeLGguULB0SA9v7VMajrTH3Ykfc=,iv:AiAwfxsZzwY/AJTISDHkmsYfB0JPlQZ9p1ldk83JKso=,tag:H8T3/RId7a8plf2AN1P9dg==,type:str]
kind: Secret
metadata:
    name: scrob-secrets
    namespace: scrob-production
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-03T17:13:55Z"
    mac: ENC[AES256_GCM,data:+tV/XXcv1d1UBkYjUmLKODirr3SkFfUMU1mUzb3Usbgl7sBYawoOLCsyGfFrq4sFHe+QvVNjeWliDZFIovFoVikpl8W2jDbq/Dm4ohBDraEbjKXr3H/WXOCZwsxNyITDU942ASkbNEU79yiQqLtzHcpeJ2k+Gx83YAM3v2qC4vs=,iv:miuGgcqPttDorxjFkKxYqTp4IvVfZXUWPI5LL8Yb3Vc=,tag:LHEUmlBnypWD3Z+EN+AAig==,type:str]
    pgp:
        - created_at: "2022-01-03T17:13:54Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA06rSFOpPqRMARAAl4FwOuXNIygXWePaOZ3IYAphRWVh19PB+uMP5z2ScT4p
            FIRlFrTviBs8vBT5dkCKafQ7c1+coZElG5ykPE95lQ3HGDei2jC5Ov5+LVlNmwJT
            BeSYkcBYLMD2fadGM+MC2xSwgUgzO04vk4Hd3eCS+A2KuYNEtVSLYYOrlMh/2VOB
            R7YjpG090ZLgbY/gXL+HQ3LL9cNMdISKHro34Kmpy84Hb1KFSyrddOlbF7F8mtLt
            EB71DerVwn8ON60/9nHaIA++ceWC4/nMoC62LpQCwh3IKdQvvvrYaaUmdSa7fYxY
            eIE2Oak6qLTovaq33gPZPvb6Sjzv4RuGEW3JLZsJCbKrZxbzxHUqLfLLw6vdkt3B
            P+SIbSR8InuMr+tloTEGKb7D1zrB2SbBb3zpXBsCWt8B3WfDGfqWgmBFRHyIaMiU
            ouLcMNyib3AiKyI7XBEEFOhA4tSb3GWUqXx28cEbe/iqkSTefsOYksBUHHiJ4Kg1
            oy83wnsJRw7PmQplNPJP+IOzhStU+tTSYNxlB98fsCGCMFEwZvz7dZHZFbLizJFV
            qTeR8u9ZvKpbyz000wHL3Pub8ACfg0kaQuqkilyN3KS/osgpc4TowGMBBFbfGAhJ
            HCnzUCQVqEr+sfIDtmjX89uySvv4lHHF235bzqo0tdKeR8oS5lSP48uh+iEvBQzS
            XgGBBBDEzoP3sbBZ69RvQ5S0hEgd09SF7q6bgvaRCFbHysCyisquvDvX7sKulZ0g
            oz6ATrLQhM/QZhWpG4TJIT2Y0p++m8ZeTSwUa5lMWaH0Nl1u6pYk0iFaim0I6CQ=
            =9W4n
            -----END PGP MESSAGE-----
          fp: A883B02E14B7EAF0A6BDAF69ECD23C5916E31D4F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
