apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: my-secrets
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 6m0s
  timeout: 4m0s
  sourceRef:
    kind: GitRepository
    name: flux-sync
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  path: ./secrets/moo-cluster
  prune: false
  wait: true
  #suspend: false
