apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster-api/aks-kuberkingdon2.yaml
- cluster-api/gke-cluster-1.yaml
- cluster-api/flux-kustomization.yaml
- cluster-api/gitrepository.yaml
- flux-system
- flux-system-extras/gitno-hephy-pro-ingress.yaml
- flux-system-extras/git-webhook-receiver.yaml
- flux-system-extras/image-webhook-receiver.yaml
- flux-system-extras/git-commit-status-alert-provider.yaml
- flux-system-extras/on-call-webapp-alert.yaml
- flux-system-extras/podinfo-image-webhook-receiver.yaml
- flux-system-extras/slack-notification.yaml
- ../../base/staging
- hephy/flux-kustomization.yaml
- metallb/flux-kustomization.yaml
- my-secrets/my-secrets-kustomization.yaml
